version: '3.8'

services:
  capture:
    build: .
    container_name: novnc_capture
    environment:
      NOVNC_URL: "https://192.168.102.49:8006/?console=kvm&novnc=1&vmid=106&vmname=mce&node=muslenka&resize=off&cmd="
    ports:
      - "8888:80"      # HLS stream
      - "6080:6080"  # noVNC web UI
    restart: unless-stopped
    shm_size: '1gb'