server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www;
    index index.html;

    location /llhls/ {
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }
        add_header Cache-Control no-cache;
    }
}